# Generated by Django 6.0.5 on 2026-05-19 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersystem.book')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersystem.buyer')),
            ],
        ),
    ]
