# Generated by Django 6.0.5 on 2026-05-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersystem.book')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersystem.buyer')),
            ],
        ),
    ]
