# Generated by Django 6.0.5 on 2026-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='Programming', max_length=100),
            preserve_default=False,
        ),
    ]
