# Generated by Django 6.0.5 on 2026-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0005_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
