# Generated by Django 6.0.5 on 2026-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0006_alter_buyer_username_alter_seller_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
