# Generated by Django 6.0.5 on 2026-05-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0007_purchase_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_approved',
            field=models.BooleanField(default=False),
        ),
    ]
