# Generated by Django 6.0.5 on 2026-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0008_purchase_payment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
