# Generated by Django 6.0.5 on 2026-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0009_purchase_payment_rejected_purchase_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No Description'),
            preserve_default=False,
        ),
    ]
