# Generated by Django 6.0.5 on 2026-05-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0010_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
    ]
