# Generated by Django 6.0.5 on 2026-05-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0011_seller_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
