# Generated by Django 6.0.5 on 2026-05-21 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0012_book_approved_book_reject_reason_book_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='upi_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='wallet_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('upi_id', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersystem.seller')),
            ],
        ),
    ]
