# Generated by Django 6.0.5 on 2026-05-21 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0013_seller_upi_id_seller_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_profiles/'),
        ),
    ]
