# Generated by Django 6.0.5 on 2026-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0015_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
