# Generated by Django 6.0.5 on 2026-05-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0016_purchase_payment_screenshot_purchase_utr_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_upi', models.CharField(max_length=200)),
            ],
        ),
    ]
