# Generated by Django 6.0.5 on 2026-05-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0017_paymentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.URLField(),
        ),
    ]
