# Generated by Django 6.0.5 on 2026-05-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0018_alter_book_cover_image_alter_book_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
