# Generated by Django 6.0.5 on 2026-05-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0020_alter_sitesettings_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
