# Generated by Django 6.0.5 on 2026-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0021_alter_buyer_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_profiles/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
    ]
