# Generated by Django 6.0.5 on 2026-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0022_alter_book_cover_image_alter_buyer_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.URLField(blank=True, null=True),
        ),
    ]
