# Generated by Django 6.0.5 on 2026-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0023_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
