# Generated by Django 6.0.5 on 2026-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0024_alter_buyer_profile_photo_alter_seller_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
